@startuml
actor User
participant ":UI" as UI
participant ":Parser" as Parser
participant ":ComputeGpaCommand" as GpaCmd
participant ":CourseRecord" as CourseRecord

User -> UI: gpa
activate UI

UI -> Parser: parse("gpa")
activate Parser
Parser -> GpaCmd: create ComputeGpaCommand()
activate GpaCmd
GpaCmd --> Parser
deactivate GpaCmd
Parser --> UI
deactivate Parser

UI -> GpaCmd: execute(ui, modules, courseRecord)
activate GpaCmd

GpaCmd -> CourseRecord: computeGpa()  
activate CourseRecord
CourseRecord --> GpaCmd: GPA value
deactivate CourseRecord

GpaCmd -> CourseRecord: computeMajorGpa() 
activate CourseRecord
CourseRecord --> GpaCmd: Major GPA value
deactivate CourseRecord

GpaCmd -> UI: showMessage("Your GPA is ...\\nYour Major GPA is ...")

activate UI
UI --> GpaCmd
deactivate UI

GpaCmd --> UI
deactivate GpaCmd

UI --> User
deactivate UI
@enduml
