@startuml
actor User
participant ":UI" as UI
participant ":Parser" as Parser
participant ":FilterCommand" as FilterCmd
participant ":ModuleList" as ModuleList

User -> UI: filter day/Monday
activate UI

UI -> Parser: parse(fullCommand)
activate Parser
Parser -> FilterCmd: create("day", "Monday")
activate FilterCmd
FilterCmd --> Parser
deactivate FilterCmd
Parser --> UI
deactivate Parser

UI -> FilterCmd: execute(ui, modules, courseRecord)
activate FilterCmd

FilterCmd -> ModuleList: findByDay("Monday")
activate ModuleList

ModuleList -> ModuleList: filter(predicate)
activate ModuleList
ModuleList --> ModuleList: filteredModules
deactivate ModuleList

ModuleList --> FilterCmd: ModuleList
deactivate ModuleList

FilterCmd -> UI: showFilteredModules(...)
activate UI
UI --> FilterCmd
deactivate UI

FilterCmd --> UI
deactivate FilterCmd

UI --> User
deactivate UI

@enduml